apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  connectionstring: SG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlO0RhdGFiYXNlPXRvZG9fZGI7VXNlcm5hbWU9dXNlcjtQYXNzd29yZD1TZWN1cmVQYXNzd29yZA==
  # Generate: echo -n "Host=postgres-service;Database=todo_db;Username=user;Password=SecurePassword" | base64